Dataset: we have 
one training data set called: iris_training.csv
one test data set called: iris_test.csv

Step 1.1, we need to read the data from our hard disk.

In [1]:
import torch
import numpy as np

# check the avaliablity of cuda(GPU) have to do that
use_cuda = torch.cuda.is_available()

# Step 1 : load data and preprocessing
# Step 1.1: Load
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"
train_data = np.genfromtxt(IRIS_TRAINING, skip_header=1, dtype=float, delimiter=',')
test_data = np.genfromtxt(IRIS_TEST, skip_header=1, dtype=float, delimiter=',')


print("train data: \n", train_data)
print("test data: \n", test_data)


train data: 
 [[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [6.9 3.1 5.1 2.3 2. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.2 2.7 3.9 1.4 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [7.7 3.8 6.7 2.2 2. ]
 [6.3 3.3 4.7 1.6 1. ]
 [6.8 3.2 5.9 2.3 2. ]
 [7.6 3.  6.6 2.1 2. ]
 [6.4 3.2 5.3 2.3 2. ]
 [5.7 4.4 1.5 0.4 0. ]
 [6.7 3.3 5.7 2.1 2. ]
 [6.4 2.8 5.6 2.1 2. ]
 [5.4 3.9 1.3 0.4 0. ]
 [6.1 2.6 5.6 1.4 2. ]
 [7.2 3.  5.8 1.6 2. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.8 2.6 4.  1.2 1. ]
 [5.9 3.  5.1 1.8 2. ]
 [5.4 3.  4.5 1.5 1. ]
 [6.7 3.  5.  1.7 1. ]
 [6.3 2.3 4.4 1.3 1. ]
 [5.1 2.5 3.  1.1 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.8 3.  5.5 2.1 2. ]
 [6.2 2.8 4.8 1.8 2. ]
 [6.9 3.2 5.7 2.3 2. ]
 [6.5 3.2 5.1 2.  2. ]
 [5.8 2.8 5.1 2.4 2. ]
 [5.1 3.8 1.5 0.3 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [7.9 3.8 6.4 2.  2. ]
 [5.8 2.7 5.1 1.9 2. ]
 [6.7 3.  5.2 2.3 2.

Step 1.2: we need to split x and y from the loaded data

In [2]:
# step 1.2
x_train = train_data[:, :4]
y_train = train_data[:, 4]

x_test = test_data[:, :4]
y_test = test_data[:, 4]

print("x_train: \n", x_train)
print("y_train: \n", y_train)
print("x_test: \n", x_test)
print("y_test: \n", y_test)

x_train: 
 [[6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [5.1 3.7 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [6.9 3.1 4.9 1.5]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.7 0.4]
 [7.7 3.8 6.7 2.2]
 [6.3 3.3 4.7 1.6]
 [6.8 3.2 5.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.4 3.2 5.3 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.1]
 [5.4 3.9 1.3 0.4]
 [6.1 2.6 5.6 1.4]
 [7.2 3.  5.8 1.6]
 [5.2 3.5 1.5 0.2]
 [5.8 2.6 4.  1.2]
 [5.9 3.  5.1 1.8]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [6.8 3.  5.5 2.1]
 [6.2 2.8 4.8 1.8]
 [6.9 3.2 5.7 2.3]
 [6.5 3.2 5.1 2. ]
 [5.8 2.8 5.1 2.4]
 [5.1 3.8 1.5 0.3]
 [4.8 3.  1.4 0.3]
 [7.9 3.8 6.4 2. ]
 [5.8 2.7 5.1 1.9]
 [6.7 3.  5.2 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.  2.2 5.  1.5]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.  3.3 1.4 0.2]
 [6.6 3.  4.4 1.4]
 

Step 2: Build the FNN model

Step 2.1: Define the hyper parameters: learning rate, hiden layer, epochs, input dim, output dim ...

In [3]:
# Step 2.1
# define hyper parameters:
input_dim = 4
hidden_dim = 32
class_num = 3
learning_rate = 0.01
epochs = 1000


Step 2.2: Build the FNN model
![](./FNN_Structure.png)

In [4]:
# Step 2.2
# Build the FNN model
import torch.nn as nn
import torch.nn.functional as F

class FNN(nn.Module):
    def __init__(self): # define the structure of modle
        super(FNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)  # z = W*x + b
        self.fc2 = nn.Linear(hidden_dim, class_num)
    
    def forward(self, x): # define the activation function
        fc1_out = F.relu(self.fc1(x))
        fc2_out = self.fc2(fc1_out)
        return fc2_out
    
fnn_net = FNN()

if use_cuda:
    fnn_net.cuda()  # If the cuda can be used, train on GPU rather than CPU
        
        

Step 2.3: Choose optimizer and loss function

In [5]:
# Step 2.3 choose optimizer and loss function
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(fnn_net.parameters(), lr=learning_rate)


Step 3: training the model

In [6]:
# Step 3: train the model
for epoch in range(epochs):
    # Step 3.1: change numpy data to tensor data:
    X = torch.Tensor(x_train).float() # dim = (|# of training samples|, feature#)
    Y = torch.Tensor(y_train).long() # dim = (|# of training samples|, 1)
    
    # Step 3.2: whether the data using GPU
    if use_cuda:
        X.cuda()
        Y.cuda()
    
    # Step 3.3: clear gradient
    optimizer.zero_grad()
        
    # Step 3.4: Feed forward
    output = fnn_net.forward(X)
    loss = criterion(output, Y)
    
    # Step 3.5: back propagation
    loss.backward() # calculate gradient
    optimizer.step() # update parameters
    
    # Step 3.6: get the accuracy on the epoch and print it
    acc = 100 * torch.sum(Y == torch.max(output.data, 1)[1]).double() / len(Y)
    # print(torch.max(output.data, 1))
    # print(torch.max(output.data, 1)[1])
    print("Epoch [%d/%d], Loss: %0.4f, Accuracy: %0.4f" % (epoch + 1, epochs, loss.item(), acc.item()))

Epoch [1/1000], Loss: 1.0426, Accuracy: 70.0000
Epoch [2/1000], Loss: 0.9961, Accuracy: 70.0000
Epoch [3/1000], Loss: 0.9634, Accuracy: 70.0000
Epoch [4/1000], Loss: 0.9391, Accuracy: 70.0000
Epoch [5/1000], Loss: 0.9203, Accuracy: 70.0000
Epoch [6/1000], Loss: 0.9053, Accuracy: 70.0000
Epoch [7/1000], Loss: 0.8928, Accuracy: 70.0000
Epoch [8/1000], Loss: 0.8820, Accuracy: 70.0000
Epoch [9/1000], Loss: 0.8724, Accuracy: 70.0000
Epoch [10/1000], Loss: 0.8635, Accuracy: 70.0000
Epoch [11/1000], Loss: 0.8553, Accuracy: 70.0000
Epoch [12/1000], Loss: 0.8474, Accuracy: 70.0000
Epoch [13/1000], Loss: 0.8398, Accuracy: 70.0000
Epoch [14/1000], Loss: 0.8325, Accuracy: 70.0000
Epoch [15/1000], Loss: 0.8253, Accuracy: 70.0000
Epoch [16/1000], Loss: 0.8183, Accuracy: 70.0000
Epoch [17/1000], Loss: 0.8114, Accuracy: 70.0000
Epoch [18/1000], Loss: 0.8046, Accuracy: 70.0000
Epoch [19/1000], Loss: 0.7980, Accuracy: 70.0000
Epoch [20/1000], Loss: 0.7914, Accuracy: 70.0000
Epoch [21/1000], Loss: 0.7850

Epoch [180/1000], Loss: 0.4442, Accuracy: 80.8333
Epoch [181/1000], Loss: 0.4434, Accuracy: 80.8333
Epoch [182/1000], Loss: 0.4427, Accuracy: 80.8333
Epoch [183/1000], Loss: 0.4419, Accuracy: 80.8333
Epoch [184/1000], Loss: 0.4411, Accuracy: 80.8333
Epoch [185/1000], Loss: 0.4404, Accuracy: 80.8333
Epoch [186/1000], Loss: 0.4396, Accuracy: 80.8333
Epoch [187/1000], Loss: 0.4389, Accuracy: 80.8333
Epoch [188/1000], Loss: 0.4381, Accuracy: 80.8333
Epoch [189/1000], Loss: 0.4374, Accuracy: 81.6667
Epoch [190/1000], Loss: 0.4367, Accuracy: 81.6667
Epoch [191/1000], Loss: 0.4359, Accuracy: 81.6667
Epoch [192/1000], Loss: 0.4352, Accuracy: 81.6667
Epoch [193/1000], Loss: 0.4345, Accuracy: 81.6667
Epoch [194/1000], Loss: 0.4337, Accuracy: 82.5000
Epoch [195/1000], Loss: 0.4330, Accuracy: 84.1667
Epoch [196/1000], Loss: 0.4323, Accuracy: 84.1667
Epoch [197/1000], Loss: 0.4316, Accuracy: 84.1667
Epoch [198/1000], Loss: 0.4308, Accuracy: 84.1667
Epoch [199/1000], Loss: 0.4301, Accuracy: 85.0000


Epoch [433/1000], Loss: 0.3106, Accuracy: 95.8333
Epoch [434/1000], Loss: 0.3103, Accuracy: 95.8333
Epoch [435/1000], Loss: 0.3099, Accuracy: 95.8333
Epoch [436/1000], Loss: 0.3095, Accuracy: 95.8333
Epoch [437/1000], Loss: 0.3091, Accuracy: 95.8333
Epoch [438/1000], Loss: 0.3087, Accuracy: 95.8333
Epoch [439/1000], Loss: 0.3083, Accuracy: 95.8333
Epoch [440/1000], Loss: 0.3079, Accuracy: 95.8333
Epoch [441/1000], Loss: 0.3075, Accuracy: 95.8333
Epoch [442/1000], Loss: 0.3071, Accuracy: 95.8333
Epoch [443/1000], Loss: 0.3068, Accuracy: 95.8333
Epoch [444/1000], Loss: 0.3064, Accuracy: 95.8333
Epoch [445/1000], Loss: 0.3060, Accuracy: 95.8333
Epoch [446/1000], Loss: 0.3056, Accuracy: 95.8333
Epoch [447/1000], Loss: 0.3052, Accuracy: 95.8333
Epoch [448/1000], Loss: 0.3048, Accuracy: 95.8333
Epoch [449/1000], Loss: 0.3045, Accuracy: 95.8333
Epoch [450/1000], Loss: 0.3041, Accuracy: 95.8333
Epoch [451/1000], Loss: 0.3037, Accuracy: 95.8333
Epoch [452/1000], Loss: 0.3033, Accuracy: 95.8333


Epoch [687/1000], Loss: 0.2302, Accuracy: 97.5000
Epoch [688/1000], Loss: 0.2299, Accuracy: 97.5000
Epoch [689/1000], Loss: 0.2297, Accuracy: 97.5000
Epoch [690/1000], Loss: 0.2294, Accuracy: 97.5000
Epoch [691/1000], Loss: 0.2292, Accuracy: 97.5000
Epoch [692/1000], Loss: 0.2289, Accuracy: 97.5000
Epoch [693/1000], Loss: 0.2287, Accuracy: 97.5000
Epoch [694/1000], Loss: 0.2284, Accuracy: 97.5000
Epoch [695/1000], Loss: 0.2282, Accuracy: 97.5000
Epoch [696/1000], Loss: 0.2279, Accuracy: 97.5000
Epoch [697/1000], Loss: 0.2277, Accuracy: 97.5000
Epoch [698/1000], Loss: 0.2274, Accuracy: 97.5000
Epoch [699/1000], Loss: 0.2272, Accuracy: 97.5000
Epoch [700/1000], Loss: 0.2270, Accuracy: 97.5000
Epoch [701/1000], Loss: 0.2267, Accuracy: 97.5000
Epoch [702/1000], Loss: 0.2265, Accuracy: 97.5000
Epoch [703/1000], Loss: 0.2262, Accuracy: 97.5000
Epoch [704/1000], Loss: 0.2260, Accuracy: 97.5000
Epoch [705/1000], Loss: 0.2257, Accuracy: 97.5000
Epoch [706/1000], Loss: 0.2255, Accuracy: 97.5000


Epoch [938/1000], Loss: 0.1803, Accuracy: 97.5000
Epoch [939/1000], Loss: 0.1801, Accuracy: 97.5000
Epoch [940/1000], Loss: 0.1800, Accuracy: 97.5000
Epoch [941/1000], Loss: 0.1798, Accuracy: 97.5000
Epoch [942/1000], Loss: 0.1797, Accuracy: 97.5000
Epoch [943/1000], Loss: 0.1795, Accuracy: 97.5000
Epoch [944/1000], Loss: 0.1794, Accuracy: 97.5000
Epoch [945/1000], Loss: 0.1792, Accuracy: 97.5000
Epoch [946/1000], Loss: 0.1790, Accuracy: 97.5000
Epoch [947/1000], Loss: 0.1789, Accuracy: 97.5000
Epoch [948/1000], Loss: 0.1787, Accuracy: 97.5000
Epoch [949/1000], Loss: 0.1786, Accuracy: 97.5000
Epoch [950/1000], Loss: 0.1784, Accuracy: 97.5000
Epoch [951/1000], Loss: 0.1783, Accuracy: 97.5000
Epoch [952/1000], Loss: 0.1781, Accuracy: 97.5000
Epoch [953/1000], Loss: 0.1780, Accuracy: 97.5000
Epoch [954/1000], Loss: 0.1778, Accuracy: 97.5000
Epoch [955/1000], Loss: 0.1777, Accuracy: 97.5000
Epoch [956/1000], Loss: 0.1775, Accuracy: 97.5000
Epoch [957/1000], Loss: 0.1774, Accuracy: 97.5000


Step 4: performance on test set:

In [7]:
# Step 4: Test the model
# Step 4.1 change data type to tensor (numpy -> tensor)
X = torch.Tensor(x_test).float()
Y = torch.Tensor(y_test).long()

if use_cuda:
    X.cuda()
    Y.cuda()

# Step 4.2: Feedforward
output = fnn_net.forward(X)

# print(output)

# Step 4.3: select the class with maximul probability:
predicted = torch.max(output.data, 1)[1]
print('Accuracy of testing %.04f %%' % (100 * torch.sum(Y == predicted).double() / len(Y)))

Accuracy of testing 96.6667 %
